src/main/java/org/eDrink24/EDrink24ServerApplication.java, src/main/java/org/eDrink24/controller/order/OrderController.java
=> [feat] test

src/main/java/org/eDrink24/controller/order/OrderController.java, src/main/resources/config/DibMapper.xml
DibMapper.xml showAllDibs에 DISTINCT 추가
OrderController.java buyProductAndSaveHistory 밑에 sysout 삭제
=> fix 필요한 코드 추가, 불필요한 코드 삭제

src/main/java/org/eDrink24/config/AppConfig.java, src/main/java/org/eDrink24/controller/login/findId/FindIdController.java, src/main/java/org/eDrink24/controller/login/findPw/FindPwController.java, src/main/java/org/eDrink24/controller/mypage/MypageCustomerController.java, src/main/java/org/eDrink24/repository/customer/CustomerRepository.java, src/main/java/org/eDrink24/service/customer/CustomerService.java, src/main/java/org/eDrink24/service/customer/CustomerServiceImpl.java
-  loginId 찾기 및 pw 찾기 및 변경기능 구현
- 비밀번호는 노출되면 안되고 email 인증 구현은 시간남을때 해야할듯
=> [feature] loginId, pw 찾기 및 pw찾기 이후 변경

src/main/java/org/eDrink24/controller/customer/CustomerController.java, src/main/java/org/eDrink24/controller/login/JwtAuthenticationController.java, src/main/java/org/eDrink24/controller/login/kakaoLogin/KakaoLoginController.java, src/main/java/org/eDrink24/domain/customer/Customer.java, src/main/java/org/eDrink24/dto/customer/CustomerDTO.java, src/main/java/org/eDrink24/dto/kakaoLogin/KakaoAccountDTO.java, src/main/java/org/eDrink24/dto/kakaoLogin/KakaoLoginResponseDTO.java, src/main/java/org/eDrink24/dto/kakaoLogin/KakaoTokenDTO.java, src/main/java/org/eDrink24/repository/customer/CustomerRepository.java, src/main/java/org/eDrink24/service/customer/KakaoLoginService.java, src/main/java/org/eDrink24/service/customer/KakaoLoginServiceImpl.java, src/main/resources/config/CustomerMapper.xml
- 카카오 로그인 API 연동 및 회원가입
- 사업자등록이 안되어있어서 일부정보만 가져올 수 있음
- 해당 정보를 통해 추가회원정보를 입력받아 로그인 진행
- 회원가입 된 회원은 바로 로그인
=> [feature] 카카오 로그인API연동

src/main/java/org/eDrink24/config/ProductMapper.java, src/main/java/org/eDrink24/controller/product/DetailProductController.java, src/main/java/org/eDrink24/service/product/ProductService.java, src/main/java/org/eDrink24/service/product/ProductServiceImpl.java, src/main/resources/config/ProductMapper.xml
- 제품 자세히보기 부분 오류 수정 ProductMapper.xml에서 showDetailProduct메소드에 파라미터로category1을 추가해주고 DetailProductController에 URL에 category1 삽입해줌
=> [fix] DetailProduct

src/main/java/org/eDrink24/config/CouponMapper.java, src/main/java/org/eDrink24/config/OrderMapper.java, src/main/java/org/eDrink24/controller/basket/BasketController.java, src/main/java/org/eDrink24/controller/coupon/CouponController.java, src/main/java/org/eDrink24/controller/order/OrderController.java, src/main/java/org/eDrink24/dto/basket/BasketItemDTO.java, src/main/java/org/eDrink24/dto/order/OrderTransactionDTO.java, src/main/java/org/eDrink24/service/basket/BasketService.java, src/main/java/org/eDrink24/service/basket/BasketServiceImpl.java, src/main/java/org/eDrink24/service/coupon/CouponService.java, src/main/java/org/eDrink24/service/coupon/CouponServiceImpl.java, src/main/java/org/eDrink24/service/order/OrderService.java, src/main/java/org/eDrink24/service/order/OrderServiceImpl.java, src/main/resources/config/BasketMapper.xml, src/main/resources/config/CouponMapper.xml, src/main/resources/config/OrderMapper.xml
deleBasketAndItem(basket, basketItem에서 구매한 상품 삭제) 기능 추가
=> feat order

src/main/java/org/eDrink24/config/BasketMapper.java, src/main/java/org/eDrink24/controller/basket/BasketController.java, src/main/java/org/eDrink24/service/basket/BasketService.java, src/main/java/org/eDrink24/service/basket/BasketServiceImpl.java, src/main/resources/config/BasketMapper.xml
- 장바구니 페이지에서 수량 변경 시에 DB에도 basketQuantity가 업데이트 되도록 수정
=> [fix] basket

src/main/java/org/eDrink24/dto/order/OrderTransactionDTO.java, src/main/resources/config/OrderMapper.xml
- 관리자페이지에서 픽업완료 버튼 클릭 후에 inventory테이블의 quantity 컬럼에서 재고가 빠져야해서 order테이블에 orderQuantity컬럼 추가해 inventory의 quantity에서 order의 orderQuantity를 빼줌.
=> [fix] order테이블에 orderQuantity 컬럼 추가

src/main/java/org/eDrink24/controller/customer/CustomerController.java, src/main/java/org/eDrink24/controller/customer/UpdateCustomerController.java, src/main/java/org/eDrink24/controller/mypage/MypageCustomerController.java, src/main/java/org/eDrink24/controller/store/StoreController.java, src/main/java/org/eDrink24/domain/customer/Customer.java, src/main/java/org/eDrink24/domain/store/Store.java, src/main/java/org/eDrink24/dto/customer/CustomerDTO.java, src/main/java/org/eDrink24/dto/store/StoreDTO.java, src/main/java/org/eDrink24/repository/customer/CustomerRepository.java, src/main/java/org/eDrink24/repository/store/StoreRepository.java, src/main/java/org/eDrink24/service/customer/CustomerService.java, src/main/java/org/eDrink24/service/customer/CustomerServiceImpl.java, src/main/java/org/eDrink24/service/store/StoreService.java, src/main/java/org/eDrink24/service/store/StoreServiceImpl.java
- 가게 정보를 찾아서 보내줌
- 근데 너무 많아서 그냥 client 쪽에 따로 store 테이블을 저장해놓음.
다만 가능하다면, client의 json파일을 스케줄링을 통해 지속적으로 업데이트 해주는 기능이 필요할듯함
=> [feture] findAllStores

src/main/java/org/eDrink24/config/AdminOrderMapper.java, src/main/java/org/eDrink24/controller/admin/AdminOrderController.java, src/main/java/org/eDrink24/dto/Inventory/InventoryDTO.java, src/main/java/org/eDrink24/dto/admin/AdminDTO.java, src/main/java/org/eDrink24/dto/order/OrderTransactionDTO.java, src/main/java/org/eDrink24/service/admin/AdminOrderService.java, src/main/java/org/eDrink24/service/admin/AdminOrderServiceImpl.java, src/main/resources/config/AdminMapper.xml, src/main/resources/config/OrderMapper.xml
발주 시 INVENTORY 테이블에 있는 상품은 quantity 증가, 없는 상품은 insert
=> feat adminOrder

src/main/java/org/eDrink24/config/AdminMapper.java, src/main/java/org/eDrink24/service/admin/AdminOrderServiceImpl.java, src/main/resources/config/AdminMapper.xml
adminOrderMapper -> adminMapper로 이름 변경
=> [fix] adminOrderMapper

src/main/java/org/eDrink24/dto/order/OrderTransactionDTO.java, src/main/resources/config/OrderMapper.xml
OrderMapper.xml, OrderTransactionDTO에서 불필요한 값 삭제
=> [fix] OrderMapper.xml

src/main/java/org/eDrink24/controller/customer/UpdateCustomerController.java, src/main/java/org/eDrink24/controller/login/JwtAuthenticationController.java, src/main/java/org/eDrink24/controller/order/OrderController.java, src/main/java/org/eDrink24/service/customer/KakaoLoginServiceImpl.java
- customer의 currentLocation, currentStoreId를 로그인시, responseEntity에 같이 보내줌
=> [fix] 로그인시, 응답메세지에 위치+매장정보 추가

src/main/java/org/eDrink24/controller/inventory/InventoryController.java, src/main/java/org/eDrink24/domain/inventory/Inventory.java, src/main/java/org/eDrink24/dto/Inventory/InventoryDTO.java, src/main/java/org/eDrink24/repository/inventory/InventoryRepository.java, src/main/java/org/eDrink24/service/inventory/InventoryService.java, src/main/java/org/eDrink24/service/inventory/InventoryServiceImpl.java
- Inventory Entity,service,controller 생성
- findAllByStoreId 메서드 생성
=> [feature] storeId로 Inventory 찾기

src/main/java/org/eDrink24/config/kakaoConfig/KakaoConfig.java, src/main/java/org/eDrink24/service/customer/KakaoLoginServiceImpl.java, src/main/resources/application.properties
- 카카오 회원가입시 currentLocation에 address1 insert되게 변경
- 카카오인증키 => properties로 이동, config/kakaoConfig로 접근
=> [fix] 카카오 회원가입 수정

src/main/java/org/eDrink24/dto/order/OrderTransactionDTO.java, src/main/resources/config/OrderMapper.xml
OrderTransactionDTO, OrderMapper.xml buyProduct에 pickupDate 추가
=> [fix] pickupDate 삽입

src/main/java/org/eDrink24/controller/store/StoreController.java, src/main/java/org/eDrink24/domain/store/Store.java, src/main/java/org/eDrink24/dto/store/StoreDTO.java, src/main/java/org/eDrink24/repository/store/StoreRepository.java, src/main/java/org/eDrink24/service/store/StoreService.java, src/main/java/org/eDrink24/service/store/StoreServiceImpl.java, src/main/resources/config/CustomerMapper.xml
- storeId로 store entity 가져오는 api
- /api/findStore/{storeId}
=> [feature] findStoreByStoreId

src/main/java/org/eDrink24/config/AdminMapper.java, src/main/java/org/eDrink24/controller/admin/AdminOrderController.java, src/main/java/org/eDrink24/dto/Inventory/InventoryDTO.java, src/main/java/org/eDrink24/dto/order/OrderTransactionDTO.java, src/main/java/org/eDrink24/service/admin/AdminOrderService.java, src/main/java/org/eDrink24/service/admin/AdminOrderServiceImpl.java, src/main/resources/config/AdminMapper.xml, src/main/resources/config/OrderMapper.xml
AdminOrder, Order 바뀐 db에 맞게 수정
=> [fix] 발주, 결제, 발주내역

src/main/java/org/eDrink24/config/BasketMapper.java, src/main/java/org/eDrink24/controller/basket/BasketController.java, src/main/java/org/eDrink24/service/basket/BasketService.java, src/main/java/org/eDrink24/service/basket/BasketServiceImpl.java, src/main/resources/config/BasketMapper.xml
INVENTORY 테이블에 들어있는 상품인지 아닌지 체크하는 existsProductInInventory메서드 생성
=> [feat] 오늘픽업/예약픽업 구분

src/main/java/org/eDrink24/config/AdminMapper.java, src/main/java/org/eDrink24/controller/admin/AdminController.java, src/main/java/org/eDrink24/dto/admin/AdminDTO.java, src/main/java/org/eDrink24/service/admin/AdminService.java, src/main/java/org/eDrink24/service/admin/AdminServiceImpl.java, src/main/resources/config/AdminMapper.xml
- AdminMapper에 메소드 이름을 오늘 픽업인지 예약 픽업인지 구분하기 위해서 변경
=> [fix] 관리자페이지

src/main/java/org/eDrink24/config/OrderMapper.java, src/main/java/org/eDrink24/config/PointMapper.java, src/main/java/org/eDrink24/controller/admin/AdminOrderController.java, src/main/java/org/eDrink24/controller/order/OrderController.java, src/main/java/org/eDrink24/controller/point/PointController.java, src/main/java/org/eDrink24/dto/coupon/CouponDTO.java, src/main/java/org/eDrink24/dto/order/OrderTransactionDTO.java, src/main/java/org/eDrink24/service/order/OrderService.java, src/main/java/org/eDrink24/service/order/OrderServiceImpl.java, src/main/java/org/eDrink24/service/point/PointService.java, src/main/java/org/eDrink24/service/point/PointServiceImpl.java, src/main/resources/config/CouponMapper.xml, src/main/resources/config/OrderMapper.xml, src/main/resources/config/PointMapper.xml
- 결제시 결제금액의 1%만큼 customer테이블 totalPoint에 적립, 포인트 사용시 결제금액에서 차감 및 사용된 포인트 totalPoint에서 차감
- 쿠폰 적용시 할인금액 적용되고 coupon 테이블 used, useDate 바뀜
=> [feat] 결제시 포인트, 쿠폰 적용

src/main/java/org/eDrink24/config/ReviewMapper.java, src/main/java/org/eDrink24/controller/review/ReviewController.java, src/main/java/org/eDrink24/dto/review/ReviewDTO.java, src/main/java/org/eDrink24/service/review/ReviewService.java, src/main/java/org/eDrink24/service/review/ReviewServiceImpl.java, src/main/resources/config/ReviewMapper.xml
- 주문내역에서 주문상태가 PICKUPED일 때, 리뷰를 저장할 수 있는 기능 구현
=> [feat] 리뷰페이지

src/main/java/org/eDrink24/config/OrderMapper.java, src/main/java/org/eDrink24/controller/order/OrderHistoryController.java, src/main/java/org/eDrink24/service/order/OrderHistoryService.java, src/main/java/org/eDrink24/service/order/OrderHistoryServiceImpl.java, src/main/resources/config/OrderMapper.xml
showOrderHistory -> orderDate별 주문내역 조회
=> [feat] 주문내역 조회

src/main/resources/config/OrderMapper.xml
=> [fix] OrderMapper.xml 수정

src/main/java/org/eDrink24/config/ProductMapper.java, src/main/java/org/eDrink24/config/appConfig/AppConfig.java, src/main/java/org/eDrink24/controller/order/OrderController.java, src/main/java/org/eDrink24/controller/payment/KakaoPayController.java, src/main/java/org/eDrink24/dto/payment/KakaoPayReadyResponse.java, src/main/java/org/eDrink24/service/customer/KakaoLoginService.java, src/main/java/org/eDrink24/service/payment/KakaoPayService.java, src/main/java/org/eDrink24/service/payment/KakaoPayServiceImpl.java, src/main/java/org/eDrink24/service/product/ProductService.java, src/main/java/org/eDrink24/service/product/ProductServiceImpl.java, src/main/resources/application.properties, src/main/resources/config/ProductMapper.xml
- KakaoPayService에서 kakaoPayReady를 통해 결제에 필요한 요청을 보내고 다음 결제에 대한 응답 URL을 받음
**issue**
- tid는 테스트결제라서 항상 같은값 => 동일 주문 에러발생 ( 실제 배포서비스가 아니므로 해결이 힘듦 )
- 예외처리를 통해 중복결제라도 성공으로 처리하도록 함
=> [feature] 카카오페이API 
